### ISSUE TITLE
Desktops Manager

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#103]
The GUI starts out way too small and compresses the drop down menus
<img width="610" alt="Screen Shot 2022-02-03 at 10 57 45 am" src="https://user-images.githubusercontent.com/90365944/152263910-de7cf432-7fda-47a1-9e09-a54575c5c54f.png">
<img width="651" alt="Screen Shot 2022-02-03 at 10 57 38 am" src="https://user-images.githubusercontent.com/90365944/152263914-c0deda91-3809-478a-b980-e1c000c2eeff.png">

**Comment by hoangnguyen177** [comment]
This should be fixed in prod.
