### ISSUE TITLE
File Converter

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#104]
File converter didn't work, didn't recognise .ims filetype

![Screen Shot 2022-02-03 at 11 17 24 am](https://user-images.githubusercontent.com/90365944/152265183-4c5e0265-c836-40a2-9636-52c0ef1a4f05.png)

**Comment by hoangnguyen177** [comment]
Fixed now! 
The script checked the whole series first, while it should check individual files.
