### ISSUE TITLE
renaming files

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#105]
error renaming files

tried to remove the date "_08.20.05"

<img width="2560" alt="Screen Shot 2022-02-03 at 11 23 31 am" src="https://user-images.githubusercontent.com/90365944/152265673-413058a1-3caa-4a2f-91b9-cd803e853e04.png">

**Comment by hoangnguyen177** [comment]
It is fixed. As I explained, the wrong config file was loaded.
