### ISSUE TITLE
opening files in CVL and possible other areas

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#106]
So I accidentally clicked the tick box for a folder, then opened the folder and selected a couple of files, and then opened them in CVL,

When I clicked on the launch ImageJ button, I got an error saying it couldn't open the folder, makes sense, but I guess it should ignore it?

I also notice the root path as well as the folder path and the file paths are all listed

<img width="2560" alt="Screen Shot 2022-02-03 at 2 01 34 pm" src="https://user-images.githubusercontent.com/90365944/152279329-48198d9d-bb94-46f8-96bd-58dc7851bf97.png">
<img width="715" alt="Screen Shot 2022-02-03 at 2 01 22 pm" src="https://user-images.githubusercontent.com/90365944/152279348-ddca945c-ffcb-4ba1-909e-d032bdc5c98f.png">
<img width="1251" alt="Screen Shot 2022-02-03 at 2 00 52 pm" src="https://user-images.githubusercontent.com/90365944/152279351-d5b76c2d-47e3-4203-8835-08c6228a6971.png">
<img width="1272" alt="Screen Shot 2022-02-03 at 2 00 43 pm" src="https://user-images.githubusercontent.com/90365944/152279353-94658a56-437e-48cc-8fe3-1606430a02bc.png">

**Comment by DrSpringy** [comment]
Also if I repeat the process of opening another file in the same CVL instance, the list of files to open isn't cleared and I get an error, but the new file does load, but in a duplicate instance of FIJI rather than the existing one

Also the copying dialog doesn't disappear off the CVL instance
<img width="1544" alt="Screen Shot 2022-02-03 at 2 06 53 pm" src="https://user-images.githubusercontent.com/90365944/152279617-90f21ba0-8d4b-4dd5-99f5-017e9bcdaddf.png">
<img width="1323" alt="Screen Shot 2022-02-03 at 2 05 51 pm" src="https://user-images.githubusercontent.com/90365944/152279641-b4c51105-7649-4796-a4f6-40bb032fa045.png">
<img width="603" alt="Screen Shot 2022-02-03 at 2 05 56 pm" src="https://user-images.githubusercontent.com/90365944/152279644-8f60176d-f152-47d7-a86a-c32c30924fb9.png">
<img width="2560" alt="Screen Shot 2022-02-03 at 2 06 04 pm" src="https://user-images.githubusercontent.com/90365944/152279646-6f817199-93ec-4e7e-aa8b-92c329f576cf.png">

**Comment by DrSpringy** [comment]
Give users an option to open in existing instance of a running application on CVL, or open a new instance

**Comment by DrSpringy** [comment]
If allowed give users an option to launch into a new CVL instance

**Comment by DrSpringy** [comment]
is there a way to notify a user (email, popup in the IPP etc) when the application has finished opening the file/s?

- System API
- Application API
- adding a task to the end of the file open script for the application to save a simple text file and monitoring for that process?

**Comment by markendr** [comment]
bug:
-file selections not clearing for next CVL session
-selecting folder does not work (should not?)

enhancement:
-CVL job status notifications, email, popup, status list
-Can macro trigger/update notification
-Send Nick open fiji file calling code
-OOD capabilities to serve some content?

**Comment by DrSpringy** [comment]
opened a single file in CVL and FIJI, then left it selected, went and found two other files and clicked file manager, deselected (X) the first file, but when CVL opened I had these errors
![Uploading Screenshot 2024-07-22 at 12.42.57 PM.png…]()

**Comment by ndasanayaka** [comment]
This issue will be resolved with the Bunya migration, as we will launch a new desktop session for each app with the selected files
