### ISSUE TITLE
collections and favourites tab - no scrollbar

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#110]
scrollbar is missing on these two tabs

**Comment by hoangnguyen177** [comment]
It probably means the list has not reached its limitation. 

When it does, the scrollbar appears automatically. 
![image](https://user-images.githubusercontent.com/555847/152464143-c326e750-7c11-46ad-8dc8-7f9248b8ffde.png)

**Comment by DrSpringy** [comment]
yeah okay, something changed because it wasn't there this morning, but is now
