### ISSUE TITLE
typo in email

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#113]
should be " You can access the output here"

<img width="578" alt="Screen Shot 2022-02-10 at 10 58 55 am" src="https://user-images.githubusercontent.com/90365944/153316517-097e6e6c-d203-4d4a-93e6-2dd36defa482.png">

**Comment by markendr** [comment]
JS, NC, ND, ME zoom call on 20-Mar-2024:

Convert to a CRM ticket and fix
