### ISSUE TITLE
Filepath copy

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#14]
copying the file path to clipboard only gets the path to the directory and not the file selected
if no file or multiple files are selected it should copy the directory file path
if one file is selected it should copy the entire files path

**Comment by hoangnguyen177** [comment]
I will add an additional button to copy path to clipboard.

/afm01/Q0/Q0703/Nikon_Example_Files/Decon_output_3/60x_1_decon.40_1x_RGB_Z008.tif

**Comment by hoangnguyen177** [comment]
added at commit 64ebe6bfed9e181ebb104baa081a4c7daa0ef91f
