### ISSUE TITLE
file copy

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#15]
I tried to make a copy of a file in the same directory and it failed
Sometimes we want to make a copy next to the original, say for PSF generation etc, so default behaviour would be to add _copy to the end of the filename if it’s in the same directory

**Comment by DrSpringy** [comment]
This still doesnt work

**Comment by markendr** [comment]
open CRM

**Comment by DrSpringy** [comment]
tested and works correctly

**Comment by DrSpringy** [comment]
except the email generated says it failed:
Slurm Job_id=666473 Name=ipp_copy Ended, Run time 00:00:00, FAILED, ExitCode 1

**Comment by ndasanayaka** [comment]
Is there an error in the slurm output?

**Comment by DrSpringy** [comment]
there's no slurm output as far as I'm aware, the containing folder just has the copied file

**Comment by ndasanayaka** [comment]
I wasn't able to reproduce the issue, and it worked fine for me. Could you please try again to see if the problem persists?

**Comment by DrSpringy** [comment]
So I get the failed email when I copy with this file and no .out file, even though it makes the copy:  /afm03/Q0/Q0703/2021-Testing/Nikon testing/60x_1.40_1x_RGB_3C_23Z.nd2

But it got a copy succeeded email with this file as well as a .out file:  /afm03/Q0/Q0703/2021-Testing/LeicaTesting/ToadNMJ_488SV_555aBTX_40X_OC.txt

Dr James Springfield
BS (Phys), MPhil (Phys), PhD (Phys)
Senior Manager - Microscopy

Institute for Molecular Bioscience
The University of Queensland
Brisbane Qld 4072 Australia

T +61 7 3346 2390
M  +61 423 021 445
E ***@***.***
Homepage<https://imb.uq.edu.au/microscopy> | YouTube<https://www.youtube.com/channel/UCbWo07HC4zHf_H1wwcoQZOQ> | Twitter<https://twitter.com/IMBmicroscopy>

Kindly ensure that IMB Microscopy is acknowledged in all publications utilising facility equipment and/or personnel.

[attachment.jpeg]

On 22 Jul 2024, at 2:29 PM, ndasanayaka ***@***.***> wrote:



I wasn't able to reproduce the issue, and it worked fine for me. Could you please try again to see if the problem persists?

**Comment by ndasanayaka** [comment]
The slurm job failed due to spaces in the destination folder. I updated the Slurm command to handle folder names with spaces, and it’s working fine now. Please test.
