### ISSUE TITLE
decon tab save/load templates

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#16]
So an issue with templates,
It doesn’t show the list of current templates, so if you create a new one with the same name, when you go to load a template theirs two with the same name, but no way to differentiate them easily except for deciphering the script.  It would be good to have ability to view all of the templates, overwrite/delete/rename and have folders so we could organise them as well as show creation date so we can differentiate a bit easier

**Comment by IMBMicroscopy** [comment]
Oh, so if you have two templates with the same name, it actually shows two and if you select one, both are selected
<img width="776" alt="Screen Shot 2021-08-31 at 8 59 26 am" src="https://user-images.githubusercontent.com/52775670/131428458-f1e66147-f802-42d4-b380-be8f73a9f2a7.png">

**Comment by IMBMicroscopy** [comment]
So loading a different shaped file and re-using a template completely breaks the decon interface
I think we need a popup saying the template is incompatible with the dataset
<img width="809" alt="Screen Shot 2021-08-31 at 9 06 40 am" src="https://user-images.githubusercontent.com/52775670/131428518-5e7d699b-15e0-4d2c-8d0f-e08ea222904b.png">
<img width="370" alt="Screen Shot 2021-08-31 at 9 06 59 am" src="https://user-images.githubusercontent.com/52775670/131428526-8aa7b658-39cd-4b23-bf81-c834c7649a79.png">
<img width="851" alt="Screen Shot 2021-08-31 at 9 06 48 am" src="https://user-images.githubusercontent.com/52775670/131428534-900fc507-9172-44da-bf75-126d7d9c2880.png">

**Comment by hoangnguyen177** [comment]
Fix the selection of two templates of the same name in version 2.1.8, deployed to test already

**Comment by hoangnguyen177** [comment]
Could you please provide the steps you took to produce the bug that breaks the decon interface ?

**Comment by IMBMicroscopy** [comment]
Save template button is now missing
<img width="878" alt="Screen Shot 2021-09-01 at 12 32 08 pm" src="https://user-images.githubusercontent.com/52775670/131602217-526fe7bd-b21e-46e5-b65f-8e267e1fb4d6.png">

**Comment by IMBMicroscopy** [comment]
oh I see, it only appears once you've checked all parameters

**Comment by IMBMicroscopy** [comment]
not highest priority, but we should be using a standard file browser/manager window for anywhere we save/load files etc
enabling things like popups to tell you do you wish to overwrite a file with the same name, copy, move, delete etc
I do like the script viewer window though, but that could be done with the text file viewer button you have

**Comment by IMBMicroscopy** [comment]
issue reusing templates, causes metadata issues
also see issues with the "browse output folder" page

https://user-images.githubusercontent.com/52775670/131613190-87a21f70-59d1-45eb-badd-bf9448f50d6f.mov


https://user-images.githubusercontent.com/52775670/131613204-3cd4f842-b28f-4d48-949d-2743bb5c22cc.mov

**Comment by DrSpringy** [comment]
Load templates isnt working,
it's not loading the illumination type, Generate PSF selection settings, iterations etc
the template shouldn't save the output file location, as templates are generally used to apply to similar but different files

**Comment by markendr** [comment]
JS, NC, DG, ND, ME zoom call on 12-Mar-2024:
- JS: deconvolution workflow breaking with templates, expecting IPP UI to be more robust/reliable
- ME/ND: looks like issues with field sync, cross-validation

Opened CRM #240314-000581 - close this issue here

**Comment by DrSpringy** [comment]
templates aren't applying to a duplicate version of the same file

**Comment by ndasanayaka** [comment]
The issue was due to a browser cache issue.  Closing the issue as it is working fine now.
