### ISSUE TITLE
Admin tab - Job submission date time

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#18]
Oh, could you have a field added to the Admin page, along with start and End, would we have submitted field, which tells us when the user clicked submit, then we can get an idea of how long it takes for different jobs to run after submission time.  Hence why it would be good to get more info about the job such as # of nodes, GPUs and memory requested etc
I put in two jobs last week for the same dataset, one job requested 1 GPU, the other requested 3GPUs, the 1GPU job was done about 5mins after submission, the 3GPU took 7 hours before it ran

**Comment by markendr** [comment]
Group with other issue on extra logging enhancement
