### ISSUE TITLE
deconvolution output

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#20]
Currently the portal outputs a single z-stack .tif for each channel, this is not the default behaviour of microvolution in FIJI on windows OS, which would output a single file containing all channels and timepoints.  However on windows OS, the user is able to split the output into separate channels and timepoints etc if required.  We require this same behaviour

**Comment by DrSpringy** [comment]
Also need to write the dimension order to the file so that it opens correctly in FIJI

[How to Import Data into FIJI.pdf](https://github.com/UQ-RCC/ipp/files/7133873/How.to.Import.Data.into.FIJI.pdf)

**Comment by hoangnguyen177** [comment]
@DrSpringy If you refresh the cache, you can split based on C, T, or C and T now. Deployed to prod.
