### ISSUE TITLE
decon - read spacing from metadata

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#22]
toggling on/off empties the spacing information and you can't get it back without reloading the dataset

**Comment by hoangnguyen177** [comment]
fixed @ 1d09a97

**Comment by hoangnguyen177** [comment]
deployed to test, version 2.1.10

**Comment by IMBMicroscopy** [comment]
still fails if you load the same template twice

**Comment by IMBMicroscopy** [comment]
even using a template, we should always read the metadata from the actual file

**Comment by DrSpringy** [comment]
merge with #16
