### ISSUE TITLE
Home page - CVL

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#23]
Add to homepage and to the email request something along the lines of:
"In order to launch a CVL job via the desktop manager you will need to have a CVL account at Wiener HPC"

**Comment by hoangnguyen177** [comment]
It is already in the homepage
![image](https://user-images.githubusercontent.com/555847/131615598-7ce954fc-3671-4c63-8214-ad8033a54326.png)

**Comment by IMBMicroscopy** [comment]
sorry I must have missed that, 
I guess I'm trying to streamline the process as much as possible and see if we can do it all in one email, with as much of the text required auto-generated for the email, rather than sending multiple emails.  but if you think that will work best we can leave it
