### ISSUE TITLE
File Manager - collections

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#25]
Use horizontal tabs to allow a user to select between the folder structure browser/Collections/Bookmarks in one narrow tall column
Ie: use the entire vertical column to view one of the tabs at a time

something like the attached image

 
![portal - file navigator](https://user-images.githubusercontent.com/52775670/131616366-d63e670c-a500-4e90-b2cd-5433b4c5d869.png)

**Comment by hoangnguyen177** [comment]
added at commit 401de0bf723cad588e63b5b9b46b7db87893b869
![image](https://user-images.githubusercontent.com/555847/132167563-47688e51-2738-4e07-ac62-008a05dbf2fc.png)

**Comment by hoangnguyen177** [comment]
deployed to test, version 2.1.10

**Comment by IMBMicroscopy** [comment]
love it
