### ISSUE TITLE
failure to glob filter files

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#28]
using preprocessing tab to merge PSFs in a folder, i used the glob filter to search for files that contains .tif, yet i get the error
<img width="1031" alt="Screen Shot 2021-09-01 at 4 17 54 pm" src="https://user-images.githubusercontent.com/52775670/131621625-3719555b-9954-4e32-8e91-a52f13879f40.png">

**Comment by IMBMicroscopy** [comment]
okay my fault, i wasnt pressing return after typing in the .tif, not obvious

**Comment by hoangnguyen177** [comment]
I think the warning message says quite clearly.
