### ISSUE TITLE
typo - home page

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#31]
"click" should be "clicking"

<img width="1125" alt="Screen Shot 2021-09-01 at 4 58 58 pm" src="https://user-images.githubusercontent.com/52775670/131626456-073b03f5-afe0-4864-b35d-f95c3dd7eba6.png">

**Comment by hoangnguyen177** [comment]
Fixed at 268e1ae

**Comment by hoangnguyen177** [comment]
Deployed to test
