### ISSUE TITLE
template email

### ISSUE THREAD

**Issue by IMBMicroscopy** [UQ-RCC/ipp#34]
amend email to send to helpdesk@qbi.uq.edu.au and rcc-support@uq.edu.au

**Comment by hoangnguyen177** [comment]
I have modified the template so that it is sent to helpdesk@qbi.... only. Send to both qbi and rcc helpdesk will confuse them.

**Comment by hoangnguyen177** [comment]
fixed @ 4399daf

**Comment by hoangnguyen177** [comment]
Deployed to test

**Comment by IMBMicroscopy** [comment]
we should just put this text in the template email, since we're emailing QBI Helpdesk anyway for the other stuff:

I will also require a CVL account at Wiener (please add me to the wiener-cvl group)

and delete this text:  In order to launch a CVL desktop via the Desktops Manager you will need to have a CVL account at Wiener. Please send an email to QBI helpdesk, explaining why you need access to CVL@Wiener, and request to be added to the wiener-cvl group.

**Comment by IMBMicroscopy** [comment]
UQ VPN - Contact UQ ITS or your institute IT team 

Add links to both

**Comment by IMBMicroscopy** [comment]
nicks working on updated documentation for how to get connected, we can then simplify the homepage to just, Why and How and some pretty pictures
