### ISSUE TITLE
Converter_OutputDirectoryNaming

### ISSUE THREAD

**Issue by NickCondon** [UQ-RCC/ipp#49]
Assuming the following Folder Structure for this example.

InputDir = \rdm\...\Imaging_data\20210908\
file.list(InputDir) = control1.ims, control2.ims, treatment1.ims, treatment2.ims

There is no assumption that all *.ims files are the same size/shape.

On the converter page i should be able to click add individual files > then select these 4 files and add them to the list.

OutputDirName = "Converter_Output"
OutputDir = InputDir+\+OutputDirName

Currently all 4 files in the list will write to this OutputDir however they currently will write into the following location: InputDir\Converter_Output\"InputDir"\control1_1.tif, control1_2.tif.... 

Unfortunately the usecase here means that files overwrite one another and the output is simply the last file processed. All 4 .out and .json are overwritten leaving just the final files .out and .json file.

Instead the output directory order/naming should be as follows:
InputDir+\+OutputDirName+\+<Filename>+\+StackName.tif

Where StackName = Filename+"_1, 2, 3, etc

By naming the subDirectory in the OutputDirectory the Filename, it will be unique (preventing overwritting files) and keep it organised/neat for future processing steps.

**Comment by hoangnguyen177** [comment]
Fixed at release 2.1.12. Deployed to test.

**Comment by hoangnguyen177** [comment]
@NickCondon @DrSpringy Please close this issue once finish testing.

**Comment by markendr** [comment]
NC to test

**Comment by NickCondon** [comment]
Some initial testing results...
Working dir = I:\IPPDATA-Q0703\Nick - Example Files\DragonflyTesting2024

No metadata.txt file = nothing works (not surprising, we should add a warning text on the converter page to alert users).

Mixed_MD is 3 different files with metadata that executed.
-Output .tif files dont have scale
-Metadata.json files are empty

Ideally output files should be within their own directory called Filename (no extension)_output within the collective output directory.

**Comment by markendr** [comment]
Thanks Nick,

We have opened CRM #240410-000752 to track (hopefully you received an email from CRM). Closing this one in github..

Regards, Mark
