### ISSUE TITLE
Files are not loading

### ISSUE THREAD

**Issue by NickCondon** [UQ-RCC/ipp#6]
Under the deconvolution tab using either Select File or Select Folder is failing to load the files.

**Comment by NickCondon** [comment]
![image](https://user-images.githubusercontent.com/40219252/75651659-c522b700-5ca4-11ea-9639-3a3701ce0f88.png)

**Comment by NickCondon** [comment]
![image](https://user-images.githubusercontent.com/40219252/75651703-f26f6500-5ca4-11ea-991a-5589176831e2.png)

(when using Select Folder)

**Comment by hoangnguyen177** [comment]
Hi Nick,

I have deployed a hot fix for the problem.

Apparently upgrading to newer version of the framework affect some behaviour with tickboxes. 

Please check.

Hoang

**Comment by hoangnguyen177** [comment]
Move to new version
