### ISSUE TITLE
Severe window flashing

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#69]
Nick has reported window flashing when using chrome

**Comment by hoangnguyen177** [comment]
@NickCondon Could you please try to see (test or prod) whether it is still happening. I have put some measures to remove the scrollbar. Tested on a windows machine as well. Release v2.1.12

**Comment by NickCondon** [comment]
Appears fixed in chrome 93.0.4577.63 (Official Build) (64-bit)
