### ISSUE TITLE
Widefield Deconvolution erroring

### ISSUE THREAD

**Issue by NickCondon** [UQ-RCC/ipp#7]
Hey Hoang, 
So widefield deconvolution is throwing a bug:

at com.microvolution.dispatch.DeconvolutionDispatch$LauncherThread.run(DeconvolutionDispatch.java:104)
Error: Parameter error: NA must be smaller than refractive index.
java.lang.RuntimeException: Parameter error: NA must be smaller than refractive index.
	at com.microvolution.DeconvolutionLauncher.InternalSetParameters(Native Method)

I have repeated this and its not a settings issue (ie same settings run interactively with no issue). Sample files/error logs are available on  q0703\Nick - Example Files\Nikon_Jess\TaDa\Decon_output

**Comment by hoangnguyen177** [comment]
Moved to new version
