### ISSUE TITLE
Deconvolution - Advanced tab - Output image type

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#71]
"32 bit (default)" should just be "32 bit"
<img width="280" alt="Screen Shot 2021-09-09 at 4 40 55 pm" src="https://user-images.githubusercontent.com/90365944/132635775-7dc5c772-301a-4698-b48e-a3d2f64ddcd9.png">

**Comment by hoangnguyen177** [comment]
Fixed in 9e46cf2
