### ISSUE TITLE
Maintenance Page - Contacts

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#76]
Probably should change it from contact Irek to contact QBI-Helpdesk

<img width="497" alt="Screen Shot 2021-09-10 at 11 41 51 am" src="https://user-images.githubusercontent.com/90365944/132785255-2e4c17cb-00ee-4c18-aa7a-d9cb407c6724.png">

**Comment by hoangnguyen177** [comment]
Done at commit 54d9153 repo ipp-homepage

**Comment by DrSpringy** [comment]
still there
<img width="1194" alt="Screen Shot 2021-09-15 at 12 09 20 pm" src="https://user-images.githubusercontent.com/90365944/133358868-b675c47e-74fe-4abf-b235-02aa11e8dd99.png">

**Comment by hoangnguyen177** [comment]
![image](https://user-images.githubusercontent.com/555847/134598019-7df4849d-2430-43b2-adc9-d25b37df010a.png)

Maybe due to caching issues.
