### ISSUE TITLE
update IMB banner

### ISSUE THREAD

**Issue by DrSpringy** [UQ-RCC/ipp#79]
<img width="583" alt="Screen Shot 2021-09-13 at 4 19 28 pm" src="https://user-images.githubusercontent.com/90365944/133033461-007ce55b-02ea-474b-b016-b7897e94efc6.png">

**Comment by hoangnguyen177** [comment]
![image](https://user-images.githubusercontent.com/555847/134599618-dff29068-657d-4720-8d4b-3274ec42c2ce.png)

Deployed to test and dev. 

Will deploy to prod this weekend.
