### ISSUE TITLE
Lost file navigator

### ISSUE THREAD

**Issue by imageprocessingportal** [UQ-RCC/ipp#85]
Narrow pages lose the file navigator, and theirs no button to bring it back<p />Additional information:<br />Current page: Filesmanager<br />Platform information: Firefox 92.0 on OS X 10.15<br />Window size(not including toolbar): 1306x937<br />Screen size: 2560x1080
 <img alt='Screen Shot 2021-09-27 at 4.31.01 pm-D82pehKvQqPpwhm7zpCM3W.png' src='https://swift.rc.nectar.org.au/v1/AUTH_d7478771a94547019f6f6bb3011ccc14/ipp_feedback_images/Screen Shot 2021-09-27 at 4.31.01 pm-D82pehKvQqPpwhm7zpCM3W.png'>

**Comment by hoangnguyen177** [comment]
This is not a bug actually. 
File navigator is hidden by design. It will appear once the browser is expanded.

**Comment by DrSpringy** [comment]
yeah that's no good, there needs to be a way to bring it up using a button if the screen is small
